OpenEvals/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'^', include('main.urls'))
]

main/urls.py
from django.conf.urls import url
from . import views

app_name='main'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'about', views.about, name='about'),
    url(r'login/$', 'django.contrib.auth.views.login', {'template_name': 'main/login.html'}, name='login'),
    url(r'logout/$', 'django.contrib.auth.views.logout', {'template_name': 'main/logout.html'},  name='logout'),
    url(r'search/(\w*)', views.search, name='search'),
    url(r'professor/([\w|\W]+)/([\w|\W]+)', views.professor, name='professor_full'), #Professor with parameter
    url(r'instructor/([\w|\W]+)/([\w|\W]+)', views.professor, name='professor_full1'),
    url(r'teacher/([\w|\W]+)/([\w|\W]+)', views.professor, name='professor_full2'),
    url(r'course/(\w+)/(\w+)', views.course, name='course_full'),
    url(r'class/(\w+)/(\w+)', views.course, name='course_full1'),
    url(r'section/(\w+)/(\w+)', views.course, name='course_full2'),
    url(r'search-autocomplete/',    views.get_results, name='search-autocomplete')

]

main/models.py
from django.db import models

class EvalQuestions(models.Model):
    number = models.IntegerField(db_column='QUESTION_NUMBER', primary_key=True)
    title = models.CharField(db_column='QUESTION_TITLE', max_length=100)
    text = models.CharField(db_column='QUESTION_TEXT', max_length=250)
    _database = "oracle"

    class Meta:
        managed = False
        db_table = '"EVAL_OWNER"."CLASS_EVAL_QUESTIONS"'

class EvalResults(models.Model):
    term_code = models.CharField(db_column='TERM_CODE', max_length=4)
    class_code = models.CharField(db_column='CLASS_CODE', max_length=30)
    class_desc = models.CharField(db_column='CLASS_DESC', max_length=100)
    instr_full_name = models.CharField(db_column='INSTR_FULL_NAME', max_length=100)
    instr_last_name = models.CharField(db_column='INSTR_LAST_NAME', max_length=50)
    instr_first_name = models.CharField(db_column='INSTR_FIRST_NAME', max_length=50)
    class_subj = models.CharField(db_column='CLASS_SUBJ',max_length=8)
    class_cat_nbr = models.CharField(db_column='CLASS_CAT_NBR', max_length=10)
    class_section = models.CharField(db_column='CLASS_SECTION', max_length=4)
    class_number = models.IntegerField(db_column='CLASS_NUMBER', primary_key=True)
    q1_average = models.DecimalField(db_column='Q1_AVERAGE', max_digits=4, decimal_places=2)
    q2_average = models.DecimalField(db_column='Q2_AVERAGE', max_digits=4, decimal_places=2)
    q3_average = models.DecimalField(db_column='Q3_AVERAGE', max_digits=4, decimal_places=2)
    q4_average = models.DecimalField(db_column='Q4_AVERAGE', max_digits=4, decimal_places=2)
    q5_average = models.DecimalField(db_column='Q5_AVERAGE', max_digits=4, decimal_places=2)
    q6_average = models.DecimalField(db_column='Q6_AVERAGE', max_digits=4, decimal_places=2)
    q7_average = models.DecimalField(db_column='Q7_AVERAGE', max_digits=4, decimal_places=2)
    q8_average = models.DecimalField(db_column='Q8_AVERAGE', max_digits=4, decimal_places=2)
    q9_average = models.DecimalField(db_column='Q9_AVERAGE', max_digits=4, decimal_places=2)
    q10_average = models.DecimalField(db_column='Q10_AVERAGE', max_digits=4, decimal_places=2)
    campus = models.CharField(db_column='CAMPUS', max_length=5)
    _database = "oracle"

    class Meta:
        managed = False
        db_table = '"EVAL_OWNER"."CLASS_EVAL_RESULTS"'

class CustomRouter(object):
    def db_for_read(self,model, **hints):
        database = getattr(model, "_database", None)
        if database:
            return database
        else:
            return "default"

    def db_for_write(self,model, **hints):
        database = getattr(model, "_database", None)
        if database:
            return database
        else:
            return "default"

    def allow_relations(self, obj1, obj2, **hints):
        return None

    def allow_migrate(self, db, model):
        if getattr(model, "_database", None):
            return False
        return True

main/forms.py
from django import forms

class SearchForm(forms.Form):
    search = forms.CharField(max_length=100,
                             widget=forms.TextInput(attrs={'class':'form-control input-lg text-center'}),
                             label='')

main/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.shortcuts import redirect
from django.shortcuts import get_list_or_404, render
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.db.models import Q
from functools import reduce
from itertools import chain
from .models import *
from .Professor import *
from .Course import *
from .forms import SearchForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
import json


def index(request):
    form = SearchForm()
    return render(request, 'main/index.html', {'search_form': form})


def about(request):
    return render(request, 'main/about.html')

def login_view(request):
    if len(request.POST) > 0:
        usern = request.POST.get('Username')
        passwd = request.POST.get('Password')
        user = authenticate(username=usern,password=passwd)
        if user is not None:
            login(request, user)
            if (request.GET.get['next']):
                return redirect(request.GET.get('next'))
            return redirect('/search/')
        else:
            return render(request, 'main/login.html')
    return render(request, 'main/login.html')
    
def logout_view(request):
    logout(request)
    return redirect('/')

@login_required
def search(request, searchQ):
    if request.method == 'GET' and len(request.GET) > 0:
        form = SearchForm(request.GET)
        if(form.is_valid()):
            if form.cleaned_data['search'].lower() == '': #csrf breaks form length test in prod
                return render(request, 'main/search.html', {'search_form': form})
            searchData = form.cleaned_data['search'].lower()
            data = searchData.split()

            foundProfs = professorsSearch(searchData)
            foundCourses = coursesSearch(data, searchData)
            return render(request, 'main/search.html', {'professors': foundProfs, "courses" : foundCourses, 'search_form' : form },)
        return render(request, 'main/search.html', {'search_form' : form})
    else:
        form = SearchForm()
        if (searchQ != ""):
            # This is solely for running a search via the common course link
            # in a professor tile. Searching via a url not yet supported
            foundCourses = coursesSearch([searchQ], searchQ)
            return render(request, 'main/search.html', {"courses": foundCourses, 'search_form': form})
        else:
            return render(request, 'main/search.html', {'search_form': form})

@login_required
def professor(request, lastname, firstname):
    form = SearchForm()
    lastname = lastname.title()
    firstname = firstname.title()
    prof = get_list_or_404(EvalResults, instr_last_name=lastname, instr_first_name=firstname)

    prof_size = len(prof)

    questions = EvalQuestions.objects.all()

    q_ratings = [0] * 10
    q_pies = [0] * 10

    # Average question ratings
    for professor in prof:
        q_ratings[0] += professor.q1_average
        q_ratings[1] += professor.q2_average
        q_ratings[2] += professor.q3_average
        q_ratings[3] += professor.q4_average
        q_ratings[4] += professor.q5_average
        q_ratings[5] += professor.q6_average
        #q_ratings[6] += professor.q7_average
        #q_ratings[7] += professor.q8_average
        #q_ratings[8] += professor.q9_average
        #q_ratings[9] += professor.q10_average
    for index in range(6):
        q_ratings[index] = round(q_ratings[index] / prof_size, 2)


    # Removes duplicate classes that the professor teaches
    seen = set()
    courses = [x for x in prof if x.class_subj + x.class_cat_nbr not in seen and not seen.add( x.class_subj + x.class_cat_nbr)]

    # Get all results for classes this professor teaches
    similar_profs_query = reduce(lambda q, course: q | Q(class_code=course.class_code), courses, Q())
    sim_profs = EvalResults.objects.filter(similar_profs_query).exclude(instr_first_name=firstname)

    # Removes duplicate professors
    prof_seen = set()
    similar_profs = [x for x in sim_profs if x.instr_full_name not in seen and not seen.add(x.instr_full_name)]

    # Creates list of Course objects
    classes = list()
    for course in courses:
        classes.append(create_course(course, firstname, lastname))

    return render(request, 'main/professor.html',
                  {'search_form': form, 'firstname': firstname, 'lastname': lastname, 'questions': questions,
                   'ratings': q_ratings, 'courses': prof, 'sim_profs': similar_profs})

    return render(request, 'main/professor.html', {'firstname': firstname,'lastname':lastname, 'questions': questions, 'ratings': q_ratings,'courses': prof,'sim_profs': similar_profs})

def create_course(course, fname, lname):
    c = Course(course.class_code,course.class_subj,course.class_cat_nbr)
    profs = EvalResults.objects.filter(class_subj=course.class_subj, class_cat_nbr=course.class_cat_nbr).exclude(instr_last_name=lname)
    for prof in profs:
        p = Professor(prof.instr_first_name, prof.instr_last_name)
        c.addProfessor(p)
        c.numSections = EvalResults.objects.filter(class_subj=course.class_subj, class_cat_nbr=course.class_cat_nbr).count()

    return c

@login_required
def course(request, subj, classcatnbr):
    #coursecode = coursecode.title()
    #coursenumber = coursenumber.title()
    sections = get_list_or_404(EvalResults, class_subj=subj, class_cat_nbr=classcatnbr)

    sections_size = len(sections)

    questions = EvalQuestions.objects.all()

    q_ratings = [0] * 10

    for courseScores in sections:
        q_ratings[0] += courseScores.q1_average
        q_ratings[1] += courseScores.q2_average
        q_ratings[2] += courseScores.q3_average
        q_ratings[3] += courseScores.q4_average
        q_ratings[4] += courseScores.q5_average
        q_ratings[5] += courseScores.q6_average
        #q_ratings[6] += courseScores.q7_average
        #q_ratings[7] += courseScores.q8_average
        #q_ratings[8] += courseScores.q9_average
        #q_ratings[9] += courseScores.q10_average

    for index in range(6):
        q_ratings[index] = round(q_ratings[index] / sections_size, 2)

    return render_to_response('main/course.html', {'subj': subj,'classcatnbr':classcatnbr, 'questions': questions, 'ratings': q_ratings, 'sections': sections})

def handler404(request):
    response = render_to_response('404.html', {}, context_instance=RequestContext(request))
    response.status_code = 404
    return response


'''
HELPER METHODS
'''


def professorsSearch(searchPOST):
    dataObjects = EvalResults.objects.all()
    startsFull = dataObjects.filter(instr_full_name__istartswith=searchPOST)  # search by first name
    startsL = dataObjects.filter(instr_last_name__istartswith=searchPOST)  # search by beginning of last name
    startsF = dataObjects.filter(instr_first_name__istartswith=searchPOST)  # search by beginning of first name
    # combine results from search methods above
    results = startsFull | startsL | startsF

    foundProfs = set()
    # sets to prevent duplicate results
    seenP = set()
    for result in results:
        seenC = set()
        if result.instr_full_name not in seenP:
            seenP.add(result.instr_full_name)
            p = Professor(result.instr_first_name, result.instr_last_name)
            # Find courses that this professor teaches
            myCourse = results.filter(instr_first_name=result.instr_first_name,
                                      instr_last_name=result.instr_last_name)
            for c in myCourse:
                if c.class_desc not in seenC:
                    seenC.add(c.class_subj)
                    p.addCourse(Course(c.class_subj, c.class_subj, str(c.class_cat_nbr), c.class_desc))

            p.setCommonCourse()
            foundProfs.add(p)
    return foundProfs


def coursesSearch(searchQuery, searchPOST):
    seenC = set()  # prevent duplicate tiles
    dataObjects = EvalResults.objects.all()
    fullName = dataObjects.filter(class_code__istartswith=searchPOST)  # search by readable name
    descName = dataObjects.filter(class_desc__contains=searchPOST)
    # separate lists because django throws a value error if you try to
    # lookup an integer database field in a list containing strings and vice versa
    subjects = list()
    numbers = list()
    # split up results in course-number format into a separate
    # list that can be used for querying the data
    for item in searchQuery:
        if '-' in item:
            subjectNumber = item.split('-')
            if len(subjectNumber) >= 2:
                try:
                    subjects.append(str(subjectNumber[0]))
                    numbers.append(int(subjectNumber[1]))
                except ValueError:
                    continue

    subjNum = dataObjects.filter(class_subj__in=subjects, class_number__in=numbers)  # search by subject-number
    if not subjNum.exists():
        subjNum = dataObjects.filter(class_subj__istartswith=searchPOST)

    # combine results from above search method
    results = fullName | subjNum | descName
    foundCourses = list()
    for result in results:
        seenP = set()
        if result.class_subj + result.class_cat_nbr not in seenC:
            seenC.add(result.class_subj + result.class_cat_nbr)
            course = Course(result.class_code, result.class_subj, result.class_cat_nbr, result.class_desc)
            #calculate how many sections there are
            allSections = results.filter(class_subj=result.class_subj, class_cat_nbr=result.class_cat_nbr)
            course.numSections = allSections.count()
            # Find campuses course is offered in
            for section in allSections:
                course.addCampus(section.campus)
            #Find professors who teach this course
            myProfessor = results.filter(class_subj=result.class_subj,

main/templates/main/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}OpenEvals{% endblock %}</title>
    {% load staticfiles %}
    {% load compress %}
    <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,300,700' rel='stylesheet' type='text/css'>
    <script src="https://code.jquery.com/jquery-1.12.2.min.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js" crossorigin="anonymous"></script>
    <script src="{% static 'js/search-autocomplete.js' %}"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    {% compress css %}
    <link rel="stylesheet" type="text/less" media="all" href="{% static 'less/style.less' %}" />
    {% endcompress %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/jquery-ui.css' %}"/>
</head>
<body>
  <nav class="header-background navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#nav-collapse" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/" style="margin-top:-3px;">
          <img src="{% static "brand.svg" %}" style="width:101px;">
        </a>
      </div>
      <div id="nav-collapse" class="navbar-collapse collapse"
            style="border: 0px none; height: 0px;">
        <ul class="nav navbar-nav navbar-left">
          <li class="">
            <a href="{% url 'main:about' %}">About</a>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li>{% if not user.is_authenticated %}
            <a href="{% url 'main:login' %}">Log In</a>
		{% endif %}
		{% if user.is_authenticated %}
	    <a href="{% url 'main:logout' %}">Log Out</a>
		{% endif %}
          </li>
        </ul>
      </div>
    </div>
  </nav>
  {% block banner %}


  {% endblock %}

      <div class="container-fluid carousel" style="background-image:url({% static "carousel.jpg" %});background-attachment:fixed; {% block cwidth %}{% endblock %}">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3" style="top:25%;
         margin-top:15px;">
        <h2 class="carousel-title text-center">OPENEVALS</h2>
        <div class="carousel-description text-center">
          <h3>{% block cdesc %}Course and Professor Evaluations.<br /> For students, by students.{% endblock %}</h3>
{% block carousel %}

            {% endblock %}</div>
        </div>


    </div>
    </div>

  {% block content %}

  {% endblock  %}
  <div class="footer">

    <div class="footer-left col-lg-6 col-md-6 col-sm-6">
      <div class="col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-4">
        <p class="footer-subtitle">
          About
        </p>
        <p style="font-size: 20px;">
          OpenEvals is the way RIT students learn about professors and courses.
        </p>
        <p style="font-size: 15px;">
          <a href="https://sg.rit.edu/">
            &copy;&nbsp;&nbsp; RIT Student Government 2016.
          </a>
          <br>
          <a href="https://github.com/ritstudentgovernment/OpenEvals">
            <span class="glyphicon glyphicon-link"></span>
            Available on GitHub.
          </a>
          <br>
          <span class="footer-version">This software is in beta.</span>
        </p>
      </div>
    </div>

    <div class="footer-right col-lg-6 col-md-6 col-sm-6">
      <div class="col-sm-6 col-sm-offset-1 col-md-4 col-md-offset-1">
        <p class="footer-subtitle">
          Learn More
        </p>
        <p>
          <a href="/about">About OpenEvals</a>
          <br>
            <a href="/search">Search</a>
          <br>
        </p>
      </div>
      <div class="col-sm-3 footer-count">
        <div class="footer-subtitle">
          Services
        </div>
        <p>
          <a href="https://pawprints.rit.edu">PawPrints</a>
          <br>
          <a href="https://ritpedia.rit.edu">RITPedia</a>
          <br>
          <a href="https://bikeshare.rit.edu">Bikeshare</a>
          <br>
          <a href="https://sites.sg.rit.edu">SG Sites</a>
        </p>
      </div>
    </div>

  </div>
</body>
</html>

main/templates/main/login.html
{% extends "main/base.html" %}

{% block title %}Log In{% endblock %}

{% block banner %}
{% load staticfiles %}

{% endblock %}
{% block carousel %}
{% endblock %}

{% block cwidth %}height: 300px;{% endblock %}

{% block content %}

{% if form.errors  %}

<div class="alert alert-danger">Incorrect username or password, or you're not a student.</div>
 {% endif %}
    <form action="{% url 'main:login' %}" method="POST">
  <div class="container">
  <div class="row"><div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3 col-xs-12">
    <div class="panel panel-default">
      <div class="panel-heading">RIT Log In</div>
        {% csrf_token %}
        <table class="table">
          <tr>
            <td><input placeholder="RIT Username" id="id_username" class="form-control"  maxlength="254" name="username" type="text"></td>
          </tr>
          <tr>
            <td><input placeholder="RIT Password" id="id_password" name="password" type="password" class="form-control"></td>
          </tr>
        </table>
        <input type="submit" value="login" class="btn btn-primary form-control" />
        <input type="hidden" name="next" value="{{ next }}" />
    </div>
  </div></div>
  </div>
</form>

{% endblock %}

main/templates/main/logout.html
{% extends "main/base.html" %}

{% block title %}Logged out of OpenEvals{% endblock %}

{% block banner %}
{% load staticfiles %}
{% endblock %}


{% block cwidth %}height: 300px;{% endblock %}
{% block cdesc %}You have been logged out!{% endblock %}

{% block content %}
<div class="container">
  <div class="panel panel-default text-center" style="padding: 50px 0 50px;">
      Remember to fill in your SmartEvals!
    </div>
  </div></div>
  </div>

{% endblock %}

main/templates/main/professor.html
{% extends "main/base.html" %}

{% block title %}Professor {{firstname}} {{lastname}}{% endblock %}

{% block banner %}
{% load staticfiles %}
{% load app_filters %}

    <!--
<div class="container-fluid campus-carousel"style="background-image:url({% static "carousel.jpg"%})">
  <div class="col-xs-12 col-sm-6 col-sm-offset-3" style="top:25%;">
    <div class="carousel-description text-center"><h1>{{firstname}} {{lastname}}</h1></div>
  </div>
</div>

-->
{% endblock %}


    <!--search bar-->
{{% block carousel %}

          <button class="btn btn-lg btn-outline-primary btn-main-search search-margin">
                Search
                <span class="glyphicon glyphicon-search carousel-search-icon"></span>
              </button>

    <form class="search-margin search-bar-hide" action="{% url 'main:search' "" %}" method="get">
            {{ search_form }}
        </form>

    <button class="btn btn-lg btn-outline-primary btn-main-search-x search-margin">
    Cancel <span class="glyphicon glyphicon-remove carousel-search-icon" aria-hidden="true"></span>
    </button>
{% endblock %}

{% block content %}
<h2 class="text-center">Summary Results</h2>
<div class="container">
  <div class="panel panel-default">
    <table class="table">
      <tr>
        <th>Question</th>
        <th>Rating</th>
      </tr>
      <tr>
        <td>{{questions.0.text}}</td>
        <td>
          <div class="progress">
            <div class="progress-bar {% if ratings.0 > 4 %} progress-bar-success {% endif %} {% if ratings.0 < 3 %} progress-bar-danger {% endif %}" role="progressbar" style="width: {% widthratio ratings.0 1 20 %}%;"></div>
          </div>
        </td>
        <td>{{ratings.0}}</td>
      </tr>
      <tr>
        <td>{{questions.1.text}}</td>
        <td>
          <div class="progress">
            <div class="progress-bar {% if ratings.0 > 4 %} progress-bar-success {% endif %} {% if ratings.0 < 3 %} progress-bar-danger {% endif %}" role="progressbar" style="width: {% widthratio ratings.1 1 20 %}%;"></div>
          </div>
        </td>
        <td>{{ratings.1}}</td>
      </tr>
<a name="results"></a>
    <h1 class="text-center" style="margin-top: 50px;">{{firstname}} {{lastname}}</h1>

<h3 class="text-center">Professor Results</h3>
<div class="container">
  <div class="panel panel-default" style="padding: 50px 0 50px;">

      <div class="col-xs-12 col-sm-6 text-center">
          <div class="c100 bigger p{{ ratings.0|convert_100 }} {{ ratings.0|color_rate }}" style="clear: both; margin-bottom: 20px;">
                <span>{{ ratings.0|convert_10 }}</span>
                <div class="slice">
                    <div class="bar"></div>
                    <div class="fill"></div>
                </div>
            </div>
          <div class="text-center" style="clear: both; margin-top: 30px; width: 350px; margin: auto;">
              {{questions.0.text}}
          </div>
      </div>
      <div class="col-xs-12 col-sm-6 text-center">
          <div class="c100 bigger p{{ ratings.1|convert_100 }} {{ ratings.1|color_rate }}" style="clear: both; margin-bottom: 20px;">
                <span>{{ ratings.1|convert_10 }}</span>
                <div class="slice">
                    <div class="bar"></div>
                    <div class="fill"></div>
                </div>
            </div>
          <div class="text-center" style="clear: both; margin-top: 30px; width: 350px; margin: auto;">
              {{questions.1.text}}
          </div>
      </div>
      <table class="table">
    </table>

  </div>
  </div>
<h2 class="text-center">Sections</h2>
<div class="container">
  <div class="row">
    {% for course in courses %}
      <div class="col-md-4">
        <div class="panel panel-default">
          <div class="panel-heading"><a href= "{% url 'main:course_full' course.class_subj course.class_cat_nbr %}" ><h3>{{ course.class_subj}}-{{ course.class_cat_nbr }}-{{course.class_section}}</h3></a></div>
          <table class="table table-striped">
            <thead>
              <th>Question</th>
              <th>Rating</th>
              <th>/5</th>
            </thead>
            <tr>
              <td>Helpful?</td>
              <td>
                <div class="progress">
                  <div class="progress-bar {% if course.q1_average > 4 %} progress-bar-success {% endif %} {% if course.q1_average < 3 %} progress-bar-danger {% endif %}" role="progressbar" style="width: {% widthratio course.q1_average 1 20 %}%;"></div>
                </div>
              </td>
              <td>{{ course.q1_average }} / 5</td>
            </tr>
            <tr>
              <td>Prompt?</td>
              <td>
                <div class="progress">
                  <div class="progress-bar {% if course.q2_average > 4 %} progress-bar-success {% endif %} {% if course.q2_average < 3 %} progress-bar-danger {% endif %}" role="progressbar" style="width: {% widthratio course.q2_average 1 20 %}%;"></div>
                </div>
              </td>
              <td>{{ course.q2_average }} / 5</td>
            </tr>
          </table>
        </div>
      </div>
    {% endfor %}
  </div>
  <div class="alert alert-danger">Missing a course? Only courses that receive enough evaluations are reflected here. Always fill out your SmartEvals surveys!</div>
</div>

{% endblock %}

main/templates/main/search.html
{% extends "main/base.html" %}

{% block title %}Search OpenEvals{% endblock %}

{% load staticfiles %}
{% block carousel %}

  <div class="container-fluid campus-carousel" style="background-image:url({% static "carousel.jpg" %})">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <div class="text-center carousel-description"><h3>Search</h3></div>
        <form class="main" action="{% url 'main:search' "" %}" method="get">
            {{ search_form }}
        </form>

{% endblock carousel %}
{% block content %}


    
  <div class="container">

  {% if not courses %}

      <div class="col-md-12 text-center">

      </div>
  {% endif %}
    <div class="col-md-6">
      <h1 class="text-center">Courses</h1>
      <div class="row">
        {% for course in courses  %}
        <a href= "{% url 'main:course_full' course.subj course.classcatnbr %}" >
          <div class="square col-xs-12">
            <div class="square-content" style="height:auto;">
              <h3 style="color:black;">{{course.subj}} - {{course.classcatnbr}}</h3>
              <h4 class="primary_link">
                {% for prof in course.professors %}
                <a href="{% url 'main:professor_full' prof.lname prof.fname %}#results" class="primary_link" >
                  {{ prof.fname }} {{ prof.lname }}&nbsp;
                </a>
                {% endfor %}
                {{ course.ellipses }}
              </h4>
              <h4 class="secondary_link">
                {% for campus in course.campus %}
                {{ campus }},
                {% endfor %}
                {{ course.numSections }} Section{% if course.numSections > 1 %}s{% endif %} 
              </h4>
            </div>
          </div>
        </a>
        {% endfor %}
      </div>
	  <div class="alert alert-danger">Missing a course? Only courses that receive enough evaluations are reflected here. Always fill out your SmartEvals surveys!</div>

    </div>
    <div class="col-md-6">
      <h1 class="text-center">Professors</h1>
      <div class="row">
        {% for prof in professors %}
        <a href= "{% url 'main:professor_full' prof.lname prof.fname  %}#results" >
          <div class="square col-xs-12">
            <div class="square-content" style="height: auto;">
              <div class="row">
                <div class="col-xs-6"><h2 style="color: black;">{{ prof.fname }} {{ prof.lname }}</h2></div>
                <div class="col-xs-6">
                  <h2 style="color: black; text-align: right">
                    <a href="{% url 'main:search' prof.commonCourse %}#results" style="color:black">
                      {{ prof.commonCourse }}
                    </a>
                  </h2>
                </div>
              </div>
              <h4>
                {% for course in prof.tileCourses %}
                <a href="{% url 'main:course_full' course.subj course.classcatnbr %}"  class="primary_link">
                  {{ course.subj }}-{{ course.classcatnbr }}&nbsp;
                </a>
                {% endfor %}
                {{ prof.ellipses }}
              </h4>
            </div>
          </div>
        </a>
        {% endfor %}
      </div>
       <div class="alert alert-danger">Missing a professor? Only professors who had courses that received enough evaluations, and that have been teaching for at least two semesters, are reflected here. Always fill out your SmartEvals surveys!</div>

    </div>

  </div>
{% block footer %}
    {{ search_form.media }}
{% endblock %}

{% endblock %}